version: '3.7'
services:
  futong-frontend-cmp2020:
    image: 172.16.71.10:15005/cmp/frontend/cmp2020:v1.6.5
    volumes:
      - /var/log/nginx:/var/log/nginx
    deploy:
      labels:
        - traefik.enable=true
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.rule=Host(`172.16.71.20`) && Method(`GET`,`POST`,`PUT`,`DELETE`,`PATCH`)"
        - traefik.http.middlewares.frontend.compress=true
        - traefik.http.routers.frontend.tls=true
        - traefik.http.services.frontend.loadbalancer.server.port=16006
      replicas: 2
      restart_policy:
        condition: any

  ftcloud-traefik:
    image: 172.16.71.10:15005/public/traefik:v2.4.8-hc
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 16000
        published: 16000
        protocol: tcp
        mode: host
      - "28080:8080"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik/:/etc/traefik/
      - /var/log/traefik:/var/log/traefik
    environment:
      - FTHC_SERVICE_NAME=normal
      - FTHC_CHECK_PORT=8082
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role==manager
