server:
  port: 8686
spring:
  application:
    name: futong-public-workflow
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ftcloud-mysql:3306/mycat_futong_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: FuTongde1gesjk
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: false
        health-check-interval: 10s
        hostname: ${spring.application.name}
        service-name: ${spring.application.name}
        enabled: true
        health-check-url: http://${spring.application.name}:${server.port}/actuator/health
      host: ftcloud-consul
      port: 8500

security:
  basic:
    enabled: false