#端口
server:
 port: 30050
spring:
  application:
    name: futong-zy-hprivate
  cloud: 
    consul: 
       host: ftcloud-consul
       port: 8500
       discovery:
         serviceName: ${spring.application.name}
         tags: futong-zy-private
         port: 30050
         instanceId: futong-zy-hprivate
         ip-address: futong-zy-hprivate
         health-check-url: http://${spring.cloud.consul.discovery.ip-address}:${spring.cloud.consul.discovery.port}/web/health
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://ftcloud-mysql:3306/itgo_monitor?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC 
    username: root
    password: FuTongde1gesjk
    type: com.zaxxer.hikari.HikariDataSource
    hikari: 
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 120000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
auth: 
  info: AUTH-INFO
jwt:
  header: X-Auth-Token
  secret: ITGO_WANHEHR
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
# 分页配置
pagehelper:
   helper-dialect: mysql
   reasonable: true
   support-methods-arguments: true
   page-size-zero: true
   params:
      count:countSql
minio:
  endpoint: ftcloud-minio
  port: 9000
  accessKey: admin
  secretKey: futongfutong
  secure: false
  bucketName: futong-zy-vreport
  configDir: /
report:
  schedule:
    day: 0 15 0 * * ?
    week: 0 20 0 ? * mon
    month: 0 30 0 01 * ?