version: '3.7'
services:
  futong-zy-compute:
    image: 119.254.93.246:15005/zy/futong-zy-compute:all
    volumes:
      - /etc/ftcloud/zy/compute:/etc/ftcloud/zy/compute
      - /var/log/ftcloud/zy/compute:/var/log/ftcloud/zy/compute
    deploy:
      replicas: 1
      restart_policy:
        condition: any