version: '3.7'
services:
  futong-zy-routetable:
    image: 119.254.93.246:15005/zy/futong-zy-routetable:all
    volumes:
      - /etc/ftcloud/zy/routetable:/etc/ftcloud/zy/routetable
      - /var/log/ftcloud/zy/routetable:/var/log/ftcloud/zy/routetable
    deploy:
      replicas: 1
      restart_policy:
        condition: any