version: '3.7'
services:
  futong-zy-nat:
    image: 119.254.93.246:15005/zy/futong-zy-nat:all
    volumes:
      - /etc/ftcloud/zy/nat:/etc/ftcloud/zy/nat
      - /var/log/ftcloud/zy/nat:/var/log/ftcloud/zy/nat
    deploy:
      replicas: 1
      restart_policy:
        condition: any