version: '3.7'
services:
  futong-zy-network:
    image: 119.254.93.246:15005/zy/futong-zy-network:all
    volumes:
      - /etc/ftcloud/zy/network:/etc/ftcloud/zy/network
      - /var/log/ftcloud/zy/network:/var/log/ftcloud/zy/network
    deploy:
      replicas: 1
      restart_policy:
        condition: any